package top.ambrat.ws.entity;

import java.util.Date;

public class CollectWorks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_works.Id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_works.user_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_works.works_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer worksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_works.collect_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Date collectTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column collect_works.status
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_works.Id
     *
     * @return the value of collect_works.Id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_works.Id
     *
     * @param id the value for collect_works.Id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_works.user_id
     *
     * @return the value of collect_works.user_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_works.user_id
     *
     * @param userId the value for collect_works.user_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_works.works_id
     *
     * @return the value of collect_works.works_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getWorksId() {
        return worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_works.works_id
     *
     * @param worksId the value for collect_works.works_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setWorksId(Integer worksId) {
        this.worksId = worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_works.collect_time
     *
     * @return the value of collect_works.collect_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_works.collect_time
     *
     * @param collectTime the value for collect_works.collect_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column collect_works.status
     *
     * @return the value of collect_works.status
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column collect_works.status
     *
     * @param status the value for collect_works.status
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}