package top.ambrat.ws.dao;

import org.apache.ibatis.jdbc.SQL;
import top.ambrat.ws.entity.Audio;

public class AudioSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio
     *
     * @mbg.generated Sat May 04 11:47:40 CST 2019
     */
    public String insertSelective(Audio record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("audio");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getUploadTime() != null) {
            sql.VALUES("upload_time", "#{uploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWorksId() != null) {
            sql.VALUES("works_id", "#{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table audio
     *
     * @mbg.generated Sat May 04 11:47:40 CST 2019
     */
    public String updateByPrimaryKeySelective(Audio record) {
        SQL sql = new SQL();
        sql.UPDATE("audio");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getUploadTime() != null) {
            sql.SET("upload_time = #{uploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWorksId() != null) {
            sql.SET("works_id = #{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}