package top.ambrat.ws.entity;

import java.util.Date;

public class Works {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.name
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.intro
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private String intro;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.view_count
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.image
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.publish_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.user_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.type_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.work_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer workTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column works.status
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.id
     *
     * @return the value of works.id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.id
     *
     * @param id the value for works.id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.name
     *
     * @return the value of works.name
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.name
     *
     * @param name the value for works.name
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.intro
     *
     * @return the value of works.intro
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.intro
     *
     * @param intro the value for works.intro
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.view_count
     *
     * @return the value of works.view_count
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.view_count
     *
     * @param viewCount the value for works.view_count
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.image
     *
     * @return the value of works.image
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.image
     *
     * @param image the value for works.image
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.publish_time
     *
     * @return the value of works.publish_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.publish_time
     *
     * @param publishTime the value for works.publish_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.user_id
     *
     * @return the value of works.user_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.user_id
     *
     * @param userId the value for works.user_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.type_id
     *
     * @return the value of works.type_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.type_id
     *
     * @param typeId the value for works.type_id
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.work_time
     *
     * @return the value of works.work_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.work_time
     *
     * @param workTime the value for works.work_time
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setWorkTime(Integer workTime) {
        this.workTime = workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column works.status
     *
     * @return the value of works.status
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column works.status
     *
     * @param status the value for works.status
     *
     * @mbg.generated Thu May 02 12:52:45 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}