package top.ambrat.ws.entity;

import java.util.Date;

public class BrowsingHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.use_id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    private Integer useId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.works_id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    private Integer worksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column browsing_history.browse_time
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    private Date browseTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.id
     *
     * @return the value of browsing_history.id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.id
     *
     * @param id the value for browsing_history.id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.use_id
     *
     * @return the value of browsing_history.use_id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public Integer getUseId() {
        return useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.use_id
     *
     * @param useId the value for browsing_history.use_id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public void setUseId(Integer useId) {
        this.useId = useId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.works_id
     *
     * @return the value of browsing_history.works_id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public Integer getWorksId() {
        return worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.works_id
     *
     * @param worksId the value for browsing_history.works_id
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public void setWorksId(Integer worksId) {
        this.worksId = worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column browsing_history.browse_time
     *
     * @return the value of browsing_history.browse_time
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public Date getBrowseTime() {
        return browseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column browsing_history.browse_time
     *
     * @param browseTime the value for browsing_history.browse_time
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public void setBrowseTime(Date browseTime) {
        this.browseTime = browseTime;
    }
}