package top.ambrat.ws.entity;

import java.util.Date;

public class Image {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.id
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.name
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.url
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.upload_time
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.works_id
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    private Integer worksId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column image.status
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.id
     *
     * @return the value of image.id
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.id
     *
     * @param id the value for image.id
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.name
     *
     * @return the value of image.name
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.name
     *
     * @param name the value for image.name
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.url
     *
     * @return the value of image.url
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.url
     *
     * @param url the value for image.url
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.upload_time
     *
     * @return the value of image.upload_time
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.upload_time
     *
     * @param uploadTime the value for image.upload_time
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.works_id
     *
     * @return the value of image.works_id
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public Integer getWorksId() {
        return worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.works_id
     *
     * @param worksId the value for image.works_id
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public void setWorksId(Integer worksId) {
        this.worksId = worksId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column image.status
     *
     * @return the value of image.status
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column image.status
     *
     * @param status the value for image.status
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}