package top.ambrat.ws.dao;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import top.ambrat.ws.entity.BrowsingHistory;

public interface BrowsingHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    @Delete({
        "delete from browsing_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    @Insert({
        "insert into browsing_history (id, use_id, ",
        "works_id, browse_time)",
        "values (#{id,jdbcType=INTEGER}, #{useId,jdbcType=INTEGER}, ",
        "#{worksId,jdbcType=INTEGER}, #{browseTime,jdbcType=TIMESTAMP})"
    })
    int insert(BrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    @InsertProvider(type=BrowsingHistorySqlProvider.class, method="insertSelective")
    int insertSelective(BrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    @Select({
        "select",
        "id, use_id, works_id, browse_time",
        "from browsing_history",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="use_id", property="useId", jdbcType=JdbcType.INTEGER),
        @Result(column="works_id", property="worksId", jdbcType=JdbcType.INTEGER),
        @Result(column="browse_time", property="browseTime", jdbcType=JdbcType.TIMESTAMP)
    })
    BrowsingHistory selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    @UpdateProvider(type=BrowsingHistorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(BrowsingHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    @Update({
        "update browsing_history",
        "set use_id = #{useId,jdbcType=INTEGER},",
          "works_id = #{worksId,jdbcType=INTEGER},",
          "browse_time = #{browseTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(BrowsingHistory record);
}