package top.ambrat.ws.dao;

import org.apache.ibatis.jdbc.SQL;
import top.ambrat.ws.entity.BrowsingHistory;

public class BrowsingHistorySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public String insertSelective(BrowsingHistory record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("browsing_history");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUseId() != null) {
            sql.VALUES("use_id", "#{useId,jdbcType=INTEGER}");
        }
        
        if (record.getWorksId() != null) {
            sql.VALUES("works_id", "#{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getBrowseTime() != null) {
            sql.VALUES("browse_time", "#{browseTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table browsing_history
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public String updateByPrimaryKeySelective(BrowsingHistory record) {
        SQL sql = new SQL();
        sql.UPDATE("browsing_history");
        
        if (record.getUseId() != null) {
            sql.SET("use_id = #{useId,jdbcType=INTEGER}");
        }
        
        if (record.getWorksId() != null) {
            sql.SET("works_id = #{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getBrowseTime() != null) {
            sql.SET("browse_time = #{browseTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}