package top.ambrat.ws.dao;

import org.apache.ibatis.jdbc.SQL;
import top.ambrat.ws.entity.CollectWorks;

public class CollectWorksSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_works
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public String insertSelective(CollectWorks record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("collect_works");
        
        if (record.getId() != null) {
            sql.VALUES("Id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getWorksId() != null) {
            sql.VALUES("works_id", "#{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getCollectTime() != null) {
            sql.VALUES("collect_time", "#{collectTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table collect_works
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public String updateByPrimaryKeySelective(CollectWorks record) {
        SQL sql = new SQL();
        sql.UPDATE("collect_works");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getWorksId() != null) {
            sql.SET("works_id = #{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getCollectTime() != null) {
            sql.SET("collect_time = #{collectTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        sql.WHERE("Id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}