package top.ambrat.ws.dao;

import org.apache.ibatis.jdbc.SQL;
import top.ambrat.ws.entity.Image;

public class ImageSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Sun May 05 10:54:14 CST 2019
     */
    public String insertSelective(Image record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("image");
        
        if (record.getId() != null) {
            sql.VALUES("id", "#{id,jdbcType=INTEGER}");
        }
        
        if (record.getName() != null) {
            sql.VALUES("name", "#{name,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
        }
        
        if (record.getUploadTime() != null) {
            sql.VALUES("upload_time", "#{uploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWorksId() != null) {
            sql.VALUES("works_id", "#{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image
     *
     * @mbg.generated Sun May 05 10:54:15 CST 2019
     */
    public String updateByPrimaryKeySelective(Image record) {
        SQL sql = new SQL();
        sql.UPDATE("image");
        
        if (record.getName() != null) {
            sql.SET("name = #{name,jdbcType=VARCHAR}");
        }
        
        if (record.getUrl() != null) {
            sql.SET("url = #{url,jdbcType=VARCHAR}");
        }
        
        if (record.getUploadTime() != null) {
            sql.SET("upload_time = #{uploadTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getWorksId() != null) {
            sql.SET("works_id = #{worksId,jdbcType=INTEGER}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=INTEGER}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }
}